name: Run shellcheck and shfmt

on:
  push:
    paths:
      - "src/*"
  pull_request:
    paths:
      - "src/*"

jobs:
  shell-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run shell-checker
        uses: luizm/action-sh-checker@v0.5.0
