name: Lint Dockerfile

on:
  push:
    paths:
      - "./Dockerfile"
  pull_request:
    paths:
      - "./Dockerfile"

jobs:
  lint-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
